### ISSUE TITLE
Number format exception

### ISSUE THREAD

**Issue by boczkas** [tomeks86/OX#43]
```
podaj rozmiar w formacie: "m n o" m - liczba wierszy (minimum 3), n - liczba kolumn (miniumum 3), o - liczba wygrywających (minimum 3 oraz nie większa niż min(m,n))
100000000000 100000000000000 5
Exception in thread "main" java.lang.NumberFormatException: For input string: "100000000000"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at edu.tseidler.service.InputParser.parseBoardSize(InputParser.java:17)
	at edu.tseidler.states.BoardSetUpState.getNextState(BoardSetUpState.java:19)
	at edu.tseidler.states.OXGame.doOneCycle(OXGame.java:52)
	at edu.tseidler.states.OXGame.start(OXGame.java:47)
	at edu.tseidler.Main.main(Main.java:9)

**Comment by kathir2vikki** [comment]
Hi 

Can you try   java.math.BigInteger BigInteger ln = new BigInteger(s); which can store the large integer value. Inside this data type you can pass the String variable.

**Comment by tomeks86** [comment]
Thank you for this suggestion but in this point I had to just catch the exception as I decided that I don't need numbers larger than 20. A ridiculously large number should lead my program to defaults :)
